# Generated by Django 5.0.6 on 2024-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images/%Y/%m/%d'),
        ),
    ]
